<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyDiem" Class="QLDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-1GUAO2R\SQLEXPRESS;Initial Catalog=QuanLyDiem;Integrated Security=True" SettingsObjectName="QuanLyDiem.Properties.Settings" SettingsPropertyName="QuanLyDiemConnectionString3" Provider="System.Data.SqlClient" />
  <Function Name="dbo.DeleteHK" Method="DeleteHK">
    <Parameter Name="maHK" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetMonHoc" Method="GetMonHoc">
    <ElementType Name="GetMonHocResult">
      <Column Name="MaMon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoTC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.HocKyAll" Method="HocKyAll">
    <ElementType Name="HocKyAllResult">
      <Column Name="MaHK" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertHK" Method="InsertHK">
    <Parameter Name="maHK" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenHK" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateHK" Method="UpdateHK">
    <Parameter Name="maHK" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenHK" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.XoaMonHoc" Method="XoaMonHoc">
    <Parameter Name="maMon" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.MonHPSelectMK" Method="MonHPSelectMK">
    <Parameter Name="maHK" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="MonHPSelectMKResult">
      <Column Name="MaMon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoTC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SuaMonHoc" Method="SuaMonHoc">
    <Parameter Name="maMon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenMon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="soTC" Type="System.Int32" DbType="Int" />
    <Parameter Name="maHK" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ThemMonHoc" Method="ThemMonHoc">
    <Parameter Name="maMon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="tenMon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="soTC" Type="System.Int32" DbType="Int" />
    <Parameter Name="maHK" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DiemHPInsert" Method="DiemHPInsert">
    <Parameter Name="maMon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maSV" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DiemHPSearch" Method="DiemHPSearch">
    <Parameter Name="maMon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maSV" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="DiemHPSearchResult">
      <Column Name="MaSV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaMon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiemHS1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemHS2" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhVienSelectAll" Method="SinhVienSelectAll">
    <ElementType Name="SinhVienSelectAllResult">
      <Column Name="MaSV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DanToc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.BangDiemHP" Method="BangDiemHP">
    <Parameter Name="malop" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mamon" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="BangDiemHPResult">
      <Column Name="MaSV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiemHS1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemHS2" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiemHP_Updatelan1" Method="DiemHP_Updatelan1">
    <Parameter Name="diemlan1" Type="System.Double" DbType="Float" />
    <Parameter Name="maMon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maSV" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DiemHP_Updatelan2" Method="DiemHP_Updatelan2">
    <Parameter Name="diemlan2" Type="System.Double" DbType="Float" />
    <Parameter Name="maMon" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="maSV" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SinhvienSelectMaLop" Method="SinhvienSelectMaLop">
    <Parameter Name="malop" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SinhvienSelectMaLopResult">
      <Column Name="MaSV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DanToc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LopAll" Method="LopAll">
    <ElementType Name="LopAllResult">
      <Column Name="MaLop" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhvienSelectID" Method="SinhvienSelectID">
    <Parameter Name="maSV" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SinhvienSelectIDResult">
      <Column Name="MaSV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DanToc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>